language: php
php:
  - 7.1
  - 7.2

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true

before_script:
  - composer install --no-interaction --no-dev
  - skeleton/riki-skeleton dev
  - cd build
  - composer install --no-interaction
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "7.1" ]; then composer require satooshi/php-coveralls:~0.6@stable; fi;'
  - mkdir -p build/logs

script:
  - composer code-style
  - bin/phpunit -c phpunit.xml --color=always --coverage-clover=build/logs/clover.xml --coverage-text
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "7.1" ]; then php vendor/bin/coveralls -v; fi;'
