#!/bin/bash

# I don't know a way how to pass arguments to this script but maybe there is one

orgOptions=$@
options=`getopt -q -o p:n: --long project-name:source-namespace: -- "$@"`
eval set -- "$options"

pGiven=false
nGiven=false
while true; do
    case "$1" in
        -p | --project-name ) pGiven=true; shift; shift ;;
        -n | --source-namespace ) nGiven=true; shift; shift ;;
        --) shift; break ;;
        * ) break ;;
    esac
done

if $pGiven && $nGiven; then
    php $(dirname $(realpath $0))/riki-skeleton setup -q "$orgOptions"
    exit 0;
fi

red=`tput setaf 1`
green=`tput setaf 2`
yellow=`tput setaf 3`
cyan=`tput setaf 6`
reset=`tput sgr0`

echo "${green}#################################################################${reset}"
echo "${green}#################################################################${reset}"
echo "${green}### ${cyan}Thanks for using riki-skeleton!                           ${green}###${reset}"
echo "${green}###                                                           ${green}###${reset}"
echo "${green}### ${reset}Unfortunately ${yellow}composer${reset} is still not able to pass stdin to ${green}###${reset}"
echo "${green}### ${reset}the post-create script. And because we need to ask you a  ${green}###${reset}"
echo "${green}### ${reset}few questions you have to start the setup manually by     ${green}###${reset}"
echo "${green}### ${reset}executing:                                                ${green}###${reset}"
echo "${green}### ${red}./setup                                                   ${green}###${reset}"
echo "${green}#################################################################${reset}"
echo "${green}#################################################################${reset}"
