#!/usr/bin/php
<?php

use Skeleton\Skeleton;

require __DIR__ . '/../vendor/autoload.php';
require __DIR__ . '/Skeleton.php';
require __DIR__ . '/Content.php';

$skeleton = new Skeleton();
$skeleton->run();
